### ISSUE TITLE
Persist of entity with non nullable association causes UnsupportedOperationException

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1077]
Mapping example:
```
@JoinColumn(name = "device_id", nullable = false)
@ManyToOne(fetch = FetchType.LAZY, targetEntity = Device.class, optional = false)
private Device device;
```

Setting either `nullable = false` or `optional = false` will cause the following exception during a persist:
```
Caused by: java.lang.UnsupportedOperationException: reactive persistence context
	at org.hibernate.reactive.engine.impl.ReactivePersistenceContextAdapter.getDatabaseSnapshot(ReactivePersistenceContextAdapter.java:76)
	at org.hibernate.engine.internal.ForeignKeys.isTransient(ForeignKeys.java:306)
	at org.hibernate.engine.internal.ForeignKeys$Nullifier.isNullifiable(ForeignKeys.java:230)
	at org.hibernate.engine.internal.ForeignKeys$Nullifier.access$000(ForeignKeys.java:36)
	at org.hibernate.engine.internal.ForeignKeys.collectNonNullableTransientEntities(ForeignKeys.java:414)
	at org.hibernate.engine.internal.ForeignKeys.findNonNullableTransientEntities(ForeignKeys.java:385)
	at org.hibernate.action.internal.AbstractEntityInsertAction.findNonNullableTransientEntities(AbstractEntityInsertAction.java:91)
	at org.hibernate.reactive.engine.ReactiveActionQueue.addInsertAction(ReactiveActionQueue.java:346)
	at org.hibernate.reactive.engine.ReactiveActionQueue.addAction(ReactiveActionQueue.java:331)
```

**Comment by blafond** [comment]
@DavideD I pushed some [tests](https://github.com/blafond/hibernate-reactive/tree/issue_1077) to a branch that replicates the error as well as starts adding the missing implementations to wrap the logic to discover any non-nullable dependent entities.

Got down to [`ReactiveEntityRegularInsertAction`](https://github.com/blafond/hibernate-reactive/blob/0d61a7d0e909a9a443a18d21b0abbd85ca2fef0a/hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactiveEntityRegularInsertAction.java#L175) which uses ForeignKeys to find/collect the relevant entities.

I'm stuck right now because most of the implementation on the ORM side is in an internal package. There's already a hibernate `ForeignKeys` class that is based on the ORM version, but it's incomplete. I started adding the missing logic to it, however, the critical utility class `NonNullableTransientDependencies` is on the interface and it's internal as well.

Not sure how to proceed to get past the hidden/private/internal ORM code.

I'll ping you first thing Monday ... with more questions :)

**Comment by DavideD** [comment]
It's a bit tricky, but at first glance you need to add a method to our [ForeignKeys](https://github.com/blafond/hibernate-reactive/blob/0d61a7d0e909a9a443a18d21b0abbd85ca2fef0a/hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java#L36) that mimics `findNonNullableTransientEntities` from the one in Hibernate ORM. The difference is that it will return a `CompletionStage<NonNullableTransientDependencies>`.

The implementation of this method needs to call the `isNullifiable` [in Reactive](https://github.com/blafond/hibernate-reactive/blob/0d61a7d0e909a9a443a18d21b0abbd85ca2fef0a/hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java#L196) (and not the one in ORM).

**Comment by blafond** [comment]
My commits start down that road... [here](https://github.com/blafond/hibernate-reactive/blob/0d61a7d0e909a9a443a18d21b0abbd85ca2fef0a/hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ForeignKeys.java#L364).

My roadblock is with ORM's `NonNullableTransientDependencies` and `ForeignKeys` internal classes.. they are `final` and access to `NonNullableTransientDependencies.add(String propertyName, Object transientEntity)` isn't available.  So implementing a reactive `ForeignKeys.collectNonNullableTransientEntities(...)` to "add" non-nullable entities isn't possible.

**Comment by DavideD** [comment]
Ok, but you don’t have to extend the classes, you need to copy and adapt  the code for the method

**Comment by DavideD** [comment]
I see now.
You can prepare a PR for Hibernate ORM that change the visibility of the `add` method and see if they are fine with it.
But the method is actually package-private, so to check if that's the only change you need, you can try moving the class in a package with the same name (`org.hibernate.engine.internal`) and see if everything works.

**Comment by DavideD** [comment]
Waiting fo rORM 5.6.7.Final
