### ISSUE TITLE
fetching snapshot from database uses JDBC

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#113]
In the following stack trace, we see that Hibernate Reactive calls JDBC. Oops.

```
 at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:75)
            at org.hibernate.persister.entity.AbstractEntityPersister.getDatabaseSnapshot(AbstractEntityPersister.java:1537)
            at org.hibernate.engine.internal.StatefulPersistenceContext.getDatabaseSnapshot(StatefulPersistenceContext.java:320)
            at org.hibernate.rx.engine.impl.RxPersistenceContextAdapter.getDatabaseSnapshot(RxPersistenceContextAdapter.java:188)
            at org.hibernate.engine.internal.ForeignKeys.isTransient(ForeignKeys.java:306)
            at org.hibernate.rx.event.impl.DefaultRxDeleteEventListener.rxOnDelete(DefaultRxDeleteEventListener.java:118)
            at org.hibernate.rx.event.impl.DefaultRxDeleteEventListener.rxOnDelete(DefaultRxDeleteEventListener.java:91)            
```

**Comment by gavinking** [comment]
So my partial fix is good, but unfortunately there's more to this. The following stack trace shows that we're going to need to rewrite an even bigger chunk of `ForeignKeys` in reactive form.

```
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:75)
	at org.hibernate.persister.entity.AbstractEntityPersister.getDatabaseSnapshot(AbstractEntityPersister.java:1540)
	at org.hibernate.engine.internal.StatefulPersistenceContext.getDatabaseSnapshot(StatefulPersistenceContext.java:320)
	at org.hibernate.rx.engine.impl.RxPersistenceContextAdapter.getDatabaseSnapshot(RxPersistenceContextAdapter.java:188)
	at org.hibernate.engine.internal.ForeignKeys.isTransient(ForeignKeys.java:306)
	at org.hibernate.engine.internal.ForeignKeys$Nullifier.isNullifiable(ForeignKeys.java:230)
	at org.hibernate.engine.internal.ForeignKeys$Nullifier.nullifyTransientReferences(ForeignKeys.java:110)
	at org.hibernate.engine.internal.ForeignKeys$Nullifier.nullifyTransientReferences(ForeignKeys.java:75)
	at org.hibernate.action.internal.AbstractEntityInsertAction.nullifyTransientReferencesIfNotAlready(AbstractEntityInsertAction.java:115)
	at org.hibernate.action.internal.AbstractEntityInsertAction.makeEntityManaged(AbstractEntityInsertAction.java:125)
	at org.hibernate.rx.engine.spi.RxActionQueue.lambda$addResolvedEntityInsertAction$4(RxActionQueue.java:346)
```

**Comment by gavinking** [comment]
So fixing this is going to be significantly more involved, but it's necessary since this bug pretty much stops you using Hibernate Reactive with manually-assigned ids.

**Comment by gavinking** [comment]
Uuuff, I thought I was most-of-the-way-done on this one (I've finished rewriting `ForeignKeys`) and now I've found that another path into `ForeignKeys.isTransient()` is via `EntityType.getIdentifier()`.

Now *that's* worrying.

It might be that we really need to go down the other path and only support assigned primitive ids with bytecode processing. WDYT, @Sanne?

**Comment by gavinking** [comment]
I've also now run into @FroMage's problem of needing to trampoline everything. This is getting crazy.

**Comment by gavinking** [comment]
Alright, so https://github.com/hibernate/hibernate-reactive/commit/f70e93cf4c0df4ae9c75d0e68269ea3c61ab4d3a "fixes" this issue, at least for the situations we currently have tests for.

I'm not at all happy with what I did here. Unless I can rewrite this code significantly, I think the performance cost (stack depth) is likely to be unacceptable.

**Comment by Sanne** [comment]
> I've also now run into @FroMage's problem of needing to trampoline everything. This is getting crazy.

"trampoline" ??

> It might be that we really need to go down the other path and only support manually assigned ids with bytecode processing.

I suppose that could be fine for Quarkus - but would you require build time enhancement for all non-Quarkus users ?
I guess we could "strongly suggest it" - in which case your fallback could be the strategy that people get when they are too lazy to bother.

**Comment by gavinking** [comment]
> "trampoline" ??

Because we don't gots no tail recursion.

There might be another solution, but I've got to try it out.

> would you require build time enhancement for all non-Quarkus users ?

Well that's the question. Precisely what does that *look* like these days, from the user point of view.

**Comment by Sanne** [comment]
> Precisely what does that look like these days, from the user point of view.

We have Gradle and Maven plugins; but it seems only selected power users actually remember to add them to their build.

WildFly does its own magic, as it controls the classloader / deployments and has a specific subsystem for Hibernate.

**Comment by Sanne** [comment]
Also to consider: enhancing entities using Hibernate version X means the packaged application gets strictly tied to version X - this is tricky for people.

So the strategies used by Quarkus and WildFly are generally preferrable, as the version coupling is enforced.

**Comment by gavinking** [comment]
Ugh, OK.

**Comment by gavinking** [comment]
This is fixed at least well enough for now.
