### ISSUE TITLE
Support for auto-generated ids of other type than Long

### ISSUE THREAD

**Issue by mjakubowski84** [hibernate/hibernate-reactive#1147]
My Postgres table generates ids of String (VARCHAR) type. Because of that hibernate-reactive-core throws an exception during insert of entities:

```
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at io.vertx.sqlclient.Tuple.getLong(Tuple.java:329)
	at org.hibernate.reactive.pool.impl.SqlClientConnection.lambda$insertAndSelectIdentifier$5(SqlClientConnection.java:177)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
```

I see that only Long ids are expected what causes the problem: https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java#L96

What is the reason for that? Is there any workaround?
Thanks in advance.

**Comment by DavideD** [comment]
You should be able to use `String` for a generated value.
The Hibernate ORM guide goes a bit more in details about it: https://docs.jboss.org/hibernate/stable/orm/userguide/html_single/Hibernate_User_Guide.html#identifiers-generators

If you give me some more info about how the id is generated in your case, I might be able to help you more.

**Comment by DavideD** [comment]
> You should be able to use `String` for a generated value.

What I mean is that it should work with the right mapping

**Comment by mjakubowski84** [comment]
Hi @DavideD.
Things are working fine with regular Hibernate. My ids are generated by trigger in Postgres. I use GeneratedValue mapping with IDENTITY generation type. For better performance I wanted to switch to reactive persistency layer. Unfortunately, it seems that hibernate-reactive supports only inserting entities that have Long id (see the linked code in my first comment).

**Comment by gavinking** [comment]
Hrm, I thought I had coded some nasty-ass special case implicit type conversion from `Long` to `Integer`. So I think I expected that to work.

**Comment by gavinking** [comment]
I wait: didn't read. You're saying your generated ids are varchars? That's weird and I'm not sure how it even works on plain Hibernate.

**Comment by gavinking** [comment]
You need to show us some code.

**Comment by mjakubowski84** [comment]
Hi @gavinking 

Here's part of the entity model:
```
@Entity(name = "entity")
public class EntityModel extends PanacheEntityBase {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String id;

}
```

And here's SQL:
```
CREATE DOMAIN entity_id AS VARCHAR(11);  -- 10 digits (1B) + string prefix

CREATE TABLE IF NOT EXISTS entity (
    id entity_id PRIMARY KEY,
    db_id SERIAL UNIQUE,
    id_type CHAR(1) NOT NULL DEFAULT 'A',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS entity_created_at_idx ON entity(created_at);
CREATE INDEX IF NOT EXISTS entity_updated_at_idx ON entity(updated_at);

-- Entity IDs can be set manually or automatically.
-- This Trigger creates an ID from the auto inc column and id type if no ID is given.

CREATE OR REPLACE FUNCTION set_entity_id()
returns trigger as $$
begin
    if new.id is null then
        new.id = new.id_type || new.db_id;
end if;
return new;
end;
$$ language 'plpgsql';

CREATE TRIGGER set_entity_id
    BEFORE INSERT ON entity
    FOR EACH ROW
    EXECUTE PROCEDURE set_entity_id();
```

As you can notice I am not using Hibernate directly but it is Panache (Quarkus), but I believe it doesn't really matter.

**Comment by gavinking** [comment]
Yeah, so, honestly: I'm almost surprised that works in ORM. (Possibly it works more by accident than by design.)

Does this change help at all: https://github.com/hibernate/hibernate-reactive/pull/1153/files

**Comment by mjakubowski84** [comment]
Thanks, I can give it a try tomorrow. But I am afraid that it is not enough. The issue is with a method I shared in my first comment: https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java#L96. `selectIdentifier` wrongly assumes that the id can be only Long and calls `getLong` on a `Row`. JDBC (VertX) actually holds there a String and that causes class cast exception. It could be solved by calling `getValue` instead which returns an Object. Later on it can be cast/transformed to a proper type as you did in the PR.

**Comment by gavinking** [comment]
Yeah, well, honestly I'm not sure that's something we're going to fix. TBH I think what you're doing here is extremely weird (and I'm very unclear on *why* you would want to jump through so many hoops to do such a strange thing). Perhaps if there's some good reasoning behind this?

**Comment by mjakubowski84** [comment]
It is a system existing for a long time (especially database). I did not try to reason much about it.

**Comment by mjakubowski84** [comment]
What would you suggest to do instead?

**Comment by gavinking** [comment]
I mean IDENTITY is clearly defined as being for database native identity columns, which is just not what you have.

**Comment by gavinking** [comment]
(On the other hand, if you propose a PR that "fixes" this for you without making a mess of my beautiful code, we will consider it.)

**Comment by gavinking** [comment]
> What would you suggest to do instead?

Well from the comment in the SQL code, one option you have is simply generating and assigning the ID in memory.

**Comment by gavinking** [comment]
> > What would you suggest to do instead?
> 
> Well from the comment in the SQL code, one option you have is simply generating and assigning the ID in memory.

Or just write a reactive Id generator that does that.

**Comment by mjakubowski84** [comment]
Thanks, I will see what can be done.

**Comment by gavinking** [comment]
Well, look, I might have changed my mind. 

I still think _your particular case_ is extremely strange and pointless-looking. You're jumping through multiple hoops in order to store a generated long integer with no business meaning as its decimal digits in a `VARCHAR` column. (Why, just to make indexing slower??!)

But, OTOH, I can imagine other cases where a trigger is used to generate a key that obeys some specific format mandated by the business, and I guess that's not *so* terrible.

So in #1153 I'm proposing a fix that will probably work for you. Let me know.

**Comment by mjakubowski84** [comment]
In my case it is not just an integer turned into varchar - it also receives a prefix which has a business meaning and is an important requirement. So the other case applies here. And I am very thankful for your PR!

**Comment by gavinking** [comment]
Oh now I see the bit about `new.id_type`. Yeah, sure, now it makes slightly more sense.

It's still bad though. 

You have a table with two unique keys: 

- `db_id` which is a true surrogate key, and can be super-efficiently stored and indexed, 
- and `id` which is a business key, and somewhat less efficient to store and index.

_Now why on God's green Earth would anyone in their right mind think to use `id` as the primary key instead of `db_id`!?_

I swear people turn their brains off as soon as they start working with SQL.

**Comment by gavinking** [comment]
> honestly: I'm almost surprised that works in ORM. (Possibly it works more by accident than by design.)

@mjakubowski84 I just asked Steve about this and he agrees that this is essentially an abuse of `@GeneratedValue(strategy = IDENTITY)`, and that if it works in core, it works by accident, not because we  intend it to be used for this sort of scenario. 

So in principle your code runs the risk of breaking in every new release of Hibernate. In practice, I don't think it's likely to break in Hibernate 6, and _certainly_ not in Hibernate 5, and so you're probably pretty safe.

Now, the "official" way to do this in Hibernate ORM is with `SelectGenerator`. But since that works via a separate database round trip, and since I we don't support `SelectGenerator` in Reactive, we're going to look into possibly introducing something better. But that would be for Hibernate 6.
