### ISSUE TITLE
Test fails on CI because it's trying to set the wrong type to a field

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1254]
This only happens occasionally and only for Oracle (it seems).
If I run the test locally, it works fine unless the test get run multiple times in a row and it will eventually fail.

```
**Gradle Test Executor 1 > org.hibernate.reactive.ReactiveStatelessProxyUpdateTest > testUpdateWithInitializedProxy STANDARD_OUT
    ERROR errors [vert.x-eventloop-thread-0] HR000057: Failed to execute statement [$1select reactivest0_.id as id1_0_0_, reactivest0_.sample_field as sample_field2_0_0_ from sample_entities reactivest0_ where reactivest0_.id=?]: $2could not load an entity: [org.hibernate.reactive.ReactiveStatelessProxyUpdateTest$SampleEntity#2]
    java.util.concurrent.CompletionException: org.hibernate.PropertyAccessException: Could not set field value [test] value by reflection : [class org.hibernate.reactive.ReactiveStatelessProxyUpdateTest$SampleEntity.sampleField] setter of org.hibernate.reactive.ReactiveStatelessProxyUpdateTest$SampleEntity.sampleField
    	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
    	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
    	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
    	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]**
```

I'm creating this issue so that we can keep track of it.

**Comment by DavideD** [comment]
Duplicates #1300
