### ISSUE TITLE
The ReactiveConnectionPoolProvider implementation is leaking threads

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#129]
When I forget to start the database and then run all integration tests, I see errors like these being logged repeatedly:

    Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "vertx-blocked-thread-checker"

I haven't verified my theory but in my experience this makes me suspect that the testsuite is leaking threads. If it's "just" the testsuite in these conditions that might not be critical, but I wonder if it could affect regular runtime.

**Comment by gavinking** [comment]
Probably related to the new schema export stuff. In which case it won't affect the runtime.

**Comment by Sanne** [comment]
Turns out I have the same problem even with databases turned on - it just takes longer to appear.

I'll try to get a profiler connected

**Comment by Sanne** [comment]
> Probably related to the new schema export stuff. In which case it won't affect the runtime.

you guessed right, threads are stuck on:

    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
	at org.hibernate.reactive.service.ReactiveGenerationTarget.accept(ReactiveGenerationTarget.java:29)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl$DelayedDropActionImpl.perform(SchemaDropperImpl.java:542)
	at org.hibernate.internal.SessionFactoryImpl.close(SessionFactoryImpl.java:792)
	at org.hibernate.reactive.BaseReactiveTest.after(BaseReactiveTest.java:75)
	at org.hibernate.reactive.CompositeIdTest.lambda$after$0(CompositeIdTest.java:39)
	at org.hibernate.reactive.CompositeIdTest$$Lambda$163/959646593.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.hibernate.reactive.impl.PoolConnection.lambda$toCompletionStage$5(PoolConnection.java:103)

Why wouldn't this affect runtime? but also, how am I supposed to launch the tests?

**Comment by gavinking** [comment]
> Why wouldn't this affect runtime?

You don't run hundreds of schema exports at runtime.

**Comment by Sanne** [comment]
> > Why wouldn't this affect runtime?
> 
> You don't run hundreds of schema exports at runtime.

Even if it's just one, we can't have a thread stuck forever?

Anyway, my OOM seems caused by running it with JDK8: with JDK11 it works.

**Comment by gavinking** [comment]
> Even if it's just one, we can't have a thread stuck forever?

It's actually only the schema dropper that has a problem, and that's probably because of how the session factory gets closed within the test suite.

If I set:

    configuration.setProperty( AvailableSettings.HBM2DDL_AUTO, "create" );

in `BaseReactiveTest`, the problem seems to disappear.

**Comment by gavinking** [comment]
Pretty sure this is fixed now.

**Comment by Sanne** [comment]
Thanks. I still have OOMs when building with JDK8 though - I can't investigate now, I'll see if I can diagnose it an evening.

**Comment by Sanne** [comment]
Ok, I was able to figure it out - I'll send a PR later.

**Comment by Sanne** [comment]
Changed the title as the problem was in the actual runtime code
