### ISSUE TITLE
NullPointerException on the console when running test on DB2

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#132]
It seems something related to Vertx and the build doesn't fail but
when I run  `DB2BasicTest` from the IDE I have the following exception:
```
rop table DB2BasicTest$Basic
io.vertx.db2client.DB2Exception: An object provided is not defined
drop sequence hibernate_sequence restrict
io.vertx.db2client.DB2Exception: An object provided is not defined
create sequence hibernate_sequence start with 1 increment by 1
[2020-05-19 19:22:38] SEVERE io.vertx.db2client.impl.codec.DB2Decoder                FATAL: Error parsing buffer at index 49 / 0x31
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 26 d0 52 00 01 00 20 22 18 00 06 11 49 00 00 |.&.R... "....I..|
|00000010| 00 16 21 10 c8 d9 e7 40 40 40 40 40 40 40 40 40 |..!....@@@@@@@@@|
|00000020| 40 40 40 40 40 40 00 0b d0 43 00 01 00 05 24 08 |@@@@@@...C....$.|
|00000030| ff 00 2b d0 52 00 02 00 25 22 0c 00 06 11 49 00 |..+.R...%"....I.|
|00000040| 04 00 05 21 15 01 00 16 21 10 c8 d9 e7 40 40 40 |...!....!....@@@|
|00000050| 40 40 40 40 40 40 40 40 40 40 40 40 00 0b d0 03 |@@@@@@@@@@@@....|
|00000060| 00 02 00 05 24 08 ff                            |....$..         |
+--------+-------------------------------------------------+----------------+
java.lang.NullPointerException
	at io.vertx.db2client.impl.drda.DRDAQueryResponse.parseEXCSQLSTTreply(DRDAQueryResponse.java:551)
	at io.vertx.db2client.impl.drda.DRDAQueryResponse.readExecute(DRDAQueryResponse.java:238)
	at io.vertx.db2client.impl.codec.ExtendedQueryCommandBaseCodec.handleUpdateResult(ExtendedQueryCommandBaseCodec.java:93)
	at io.vertx.db2client.impl.codec.ExtendedQueryCommandCodec.decodeUpdate(ExtendedQueryCommandCodec.java:57)
	at io.vertx.db2client.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:71)
	at io.vertx.db2client.impl.codec.DB2Decoder.decodePayload(DB2Decoder.java:80)
	at io.vertx.db2client.impl.codec.DB2Decoder.decode(DB2Decoder.java:53)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

I've started the container using:
```
sudo podman run --rm -it -e LICENSE=accept --privileged=true --name HibernateTestingDB2 -e DBNAME=$DATABASE -e DB2INSTANCE=$USERNAME -e DB2INST1_PASSWORD=$PASSWORD -p 50000:50000 ibmcom/db2
```

**Comment by DavideD** [comment]
@aguibert ^

**Comment by aguibert** [comment]
I tried this a few different ways and wasn't able to reproduce the issue. What values were you using for the env variables?

Here is what I used:
```
DBNAME=hib_rx
USERNAME=hib_rx
PASSWORD=hibernate-rx
```

If that's the same as what you have, can you enable logging (`showStandardStreams=true` in build.gradle) and upload logs?

**Comment by aguibert** [comment]
@DavideD never mind, I was able to reproduce this issue now and will work on a fix

**Comment by DavideD** [comment]
Thanks @aguibert

**Comment by aguibert** [comment]
Will be fixed by: https://github.com/eclipse-vertx/vertx-sql-client/pull/649

**Comment by DavideD** [comment]
Thanks a lot!
