### ISSUE TITLE
Getting Flux<Entity> from CompletionStage failing in hibernate-reactive 2.0.0.Alpha2

### ISSUE THREAD

**Issue by radovanradic** [hibernate/hibernate-reactive#1523]
Hello,

Maybe not the best title, but this is basically what we are having issue with. In hibernate5 and hibernate-reactive 1.1.9 the same code works fine.
This is the method 
```
public Flux<Pet> findAll() {
        return withSessionFlux(session -> Mono.fromCompletionStage(() -> session.createQuery("from Pet", Pet.class)
                        .getResultList()
                        .thenCompose(pets -> {
                            // HR000037: Reactive sessions do not support transparent lazy fetching
                            // - use Session.fetch() (entity 'example.domain.Owner' with id '1' was not loaded)
                            CompletableFuture<List<Pet>> result = CompletableFuture.completedFuture(new ArrayList<>());
                            for (Pet pet : pets) {
                                result = result.thenCombine(session.fetch(pet.getOwner()), (newPets, owner) -> {
                                    pet.setOwner(owner);
                                    newPets.add(pet);
                                    return newPets;
                                });
                            }
                            return result;
                        }))
                .flatMapMany(Flux::fromIterable));
    }
```

And when called like this (mapper converts to Dto, accessing Owner that is being fetched to avoid lazy load error)
```
Flux<Pet> petsFlux = petRepository.findAll();
Mapper mapper = new Mapper();
Mono<List<PetDto>> monoPets = petsFlux.map(mapper::toPetDto).collectList();
List<PetDto> pets = monoPets.block();
```
 it is throwing this error

```
Exception in thread "main" java.lang.IllegalStateException: Illegal pop() with non-matching JdbcValuesSourceProcessingState
	at org.hibernate.sql.results.spi.LoadContexts.deregister(LoadContexts.java:46)
	at org.hibernate.reactive.sql.results.spi.ReactiveListResultsConsumer.finishUp(ReactiveListResultsConsumer.java:184)
	at org.hibernate.reactive.sql.results.spi.ReactiveListResultsConsumer.lambda$consume$3(ReactiveListResultsConsumer.java:117)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
```
Here is the example app
[hib-reactive-issue-list.zip](https://github.com/hibernate/hibernate-reactive/files/11020654/hib-reactive-issue-list.zip)

And the same app with hibernate5 and hibernate-reactive 1.1.9 that works fine 
[hib-reactive-issue-list-hibernate5.zip](https://github.com/hibernate/hibernate-reactive/files/11020659/hib-reactive-issue-list-hibernate5.zip)

Should we change how we work around issue with lazy load exception or this is some bug in hibernate-reactive 2.0.0.Alpha2?

Thanks,
Radovan

**Comment by DavideD** [comment]
The problem is that when you use `.thenCombine` you will end up using the same session in multiple streams. This sometime might work but it's not something that should be relied on. [The same session cannot be used in parallel streams](https://hibernate.org/reactive/documentation/1.1/reference/html_single/#_sessions_and_vert_x_contexts)

The reason this fails now is because Hibernate Reactive 2 is based on ORM 6.2 and it contains better error detection.

The code will work if you change it to:

```java
    public Flux<Pet> findAll() {
        return withSessionFlux(session -> Mono.fromCompletionStage(() -> session.createQuery("from Pet", Pet.class)
                        .getResultList()
                        .thenCompose(pets -> {
                            CompletableFuture<List<Pet>> resultStage = CompletableFuture.completedFuture( new ArrayList<>() );
                            for (Pet pet : pets) {
                                resultStage = resultStage
                                        .thenCompose( newPets -> session
                                                .fetch( pet.getOwner() )
                                                .thenApply( owner -> {
                                                    pet.setOwner( owner );
                                                    newPets.add( pet );
                                                    return newPets;
                                                } )
                                        );
                            }
                            return resultStage;
                        }))
                .flatMapMany(Flux::fromIterable));
    }
```

We definitely need to improve the error message

**Comment by radovanradic** [comment]
Thanks alot @DavideD, it works fine with your suggested change.
