### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by alxxyz** [hibernate/hibernate-reactive#1530]
We are using MSSQL client
```
<dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-mssql-client</artifactId>
            <version>4.3.4</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate.reactive</groupId>
            <artifactId>hibernate-reactive-core</artifactId>
            <version>1.1.9.Final</version>
        </dependency>
```
and when we send a query we are getting this error
```
ERROR 14760 --- [ntloop-thread-0] org.hibernate.reactive.errors            : HR000057: Failed to execute statement [select ...]: could not execute query

java.util.concurrent.CompletionException: java.net.SocketException: Connection reset
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[na:na]
	at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:386) ~[vertx-core-4.3.4.jar:4.3.4]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[vertx-core-4.3.4.jar:4.3.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.3.4.jar:4.3.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.3.4.jar:4.3.4]
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[vertx-core-4.3.4.jar:4.3.4]
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryFail(QueryResultBuilder.java:116) ~[vertx-sql-client-4.3.4.jar:4.3.4]
```
What could be wrong?

**Comment by DavideD** [comment]
Hard to say. It seems there was a failure executing one query.
Can you provide a test case or a project showing the error?

**Comment by alxxyz** [comment]
It doesn't fail on each databases, so it is hard to provide a test project, it works with testcontainers.
We also tried to use just `vertx-mssql-client`, and it works with the databases, which fail with `hibernate-reactive`

**Comment by DavideD** [comment]
I don't think this is enough info for helping you. 
Maybe the error will go away with the next release
