### ISSUE TITLE
new @SQLSelect annotation does not work

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#1627]
If I add:

    @SQLSelect(sql = "select name, id from authors where id = $1")

to `org.hibernate.reactive.example.nativesql.Author`, I get:

```
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.Collections$EmptyIterator.next(Collections.java:4210)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1047)
	at org.hibernate.reactive.loader.ast.internal.ReactiveSingleIdEntityLoaderProvidedQueryImpl.load(ReactiveSingleIdEntityLoaderProvidedQueryImpl.java:51)
	at org.hibernate.reactive.loader.ast.internal.ReactiveSingleIdEntityLoaderProvidedQueryImpl.load(ReactiveSingleIdEntityLoaderProvidedQueryImpl.java:27)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractPersisterDelegate.load(ReactiveAbstractPersisterDelegate.java:235)
	at org.hibernate.reactive.persister.entity.impl.ReactiveSingleTableEntityPersister.doReactiveLoad(ReactiveSingleTableEntityPersister.java:272)
```

This issue appears to be that the `$1` is not recognized. But changing it to `?` or `?1` does not seem to help.

**Comment by blafond** [comment]
@Davide Pushed a commit of a Reactive version of ORM's `SQLSelectTest` to my repo:  https://github.com/blafond/hibernate-reactive/commit/e88effdb4ba0a994a3c2c6a68535daed44ba1d9a on a [1627-sqlselect](https://github.com/blafond/hibernate-reactive/commits/1627-sqlselect) branch

I think the current errors are due to two things that are missing in Reactive.

1. During the [ReactiveSingleIdEntityLoaderProvidedQueryImpl.load()](https://github.com/hibernate/hibernate-reactive/blob/29c518e2209362745f7c3e186442504e3d524acf/hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleIdEntityLoaderProvidedQueryImpl.java#L47) call, the `query` object is an instance of a `AbstractSelectionQuery` rather than a `ReactiveAbstractSelectionQuery` so `query.uniqueResult()` is called rather than the reactive method: `reactiveUnique`
2. The parameter parsing for `AbstractSelectionQuery ` is using the ORM's `ParameterParser` which only looks for the `?` placeholder ... so using `$1` won't work

**Comment by DavideD** [comment]
Also, this seems very wrong: https://github.com/hibernate/hibernate-reactive/blob/29c518e2209362745f7c3e186442504e3d524acf/hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ast/internal/ReactiveSingleIdEntityLoaderProvidedQueryImpl.java#L54

**Comment by blafond** [comment]
thx.. been working on this and pushed a couple changes more [changes](https://github.com/blafond/hibernate-reactive/commit/c0c393aa50e691e3b5b2291a5bd6585e7886c1ca).
