### ISSUE TITLE
vertx errors logged in test suite

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#166]
I have started seeing a couple of these in the log:

```
[2020-05-22 11:56:10] SEVERE io.vertx.core.impl.ContextImpl                          Unhandled exception
java.lang.IllegalStateException
	at io.vertx.sqlclient.impl.ConnectionPool$PooledConnection.close(ConnectionPool.java:132)
	at io.vertx.sqlclient.impl.SqlConnectionImpl.close(SqlConnectionImpl.java:127)
	at io.vertx.sqlclient.impl.SqlConnectionImpl.lambda$close$5(SqlConnectionImpl.java:130)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Any idea, @Sanne?

**Comment by Sanne** [comment]
I don't see this. Are you running any specific test? or inspecting the logs from the full build?

FWIW, I was never able to run the DB2 test successfully - so I'm ignoring that one ATM

**Comment by DavideD** [comment]
I remember seeing a lot of them in the past but they disappeared at some point. Where do you see them?

**Comment by gavinking** [comment]
> Where do you see them?

When running tests in the IDE. But there's rather a lot of output so you have to kinda hunt for them.

**Comment by gavinking** [comment]
Yay, these seem to be gone now. Surely to do with my work on schema drop.
