### ISSUE TITLE
IllegalAccessError thrown from ReactiveQuerySqmImpl

### ISSUE THREAD

**Issue by oleg-alexeyev** [hibernate/hibernate-reactive#1725]
Running tests which use Hibernate Reactive in TeamCity causes the following exception to be thrown (now that #1682 is fixed, it's possible to get the stacktrace).

`AbstractSelectionQuery.uniqueElement()` is protected and `ReactiveQuerySqmImpl` is a subclass of `AbstractSelectionQuery`, but they're in different modules (`hibernate-reactive-core-2.0.3.Final.jar` and `hibernate-core-6.2.6.Final.jar`). Could it be the reason?

```
...
Caused by: java.lang.IllegalAccessError: class org.hibernate.reactive.query.sqm.internal.ReactiveQuerySqmImpl$$Lambda$10815/0x00000008051d6ca8 tried to access protected method 'java.lang.Object org.hibernate.query.spi.AbstractSelectionQuery.uniqueElement(java.util.List)' (org.hibernate.reactive.query.sqm.internal.ReactiveQuerySqmImpl$$Lambda$10815/0x00000008051d6ca8 and org.hibernate.query.spi.AbstractSelectionQuery are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @ea4007e)
		at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
		at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.unroll(AsyncTrampoline.java:131)
		at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.lambda$unroll$0(AsyncTrampoline.java:126)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
		at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:536)
		at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
		at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
		at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
		at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
		at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:88)
		at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:32)
		at io.vertx.core.Promise.complete(Promise.java:66)
		at io.vertx.core.Promise.handle(Promise.java:51)
		at io.vertx.core.Promise.handle(Promise.java:29)
		at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
		at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
		at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
		at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
		at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
		at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
		at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
		at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
		at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
		at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
		at io.vertx.core.impl.future.Transformation$1.onSuccess(Transformation.java:63)
		at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
		at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
		at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
		at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:44)
		at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by oleg-alexeyev** [comment]
> Out of curiosity, how are you running the query?

Something like this:
```kotlin
suspend fun find(s: Mutiny.Session, id: String): Entity? {
        return s.createQuery<ConfigEntity>("FROM Entity WHERE id = :id")
            .setParameter("id", id)
            .singleResultOrNull
            .awaitSuspending()
}
```

**Comment by DavideD** [comment]
@oleg-alexeyev, I have a couple of questions:

* Would you be able to test this without Kotlin? (Maybe you can also try to not use a suspend method)
* Does the error happen only when you run integration tests on CI? Or does it happen during live reload?

We could change the scope of the method, but this seems like something else is wrong.

**Comment by oleg-alexeyev** [comment]
After long hunting the issue was identified - some build agent had an early access, pre-release version of OpenJDK 17. Upgrading it solved the issue. Sorry for the hassle, and thanks for understanding!
