### ISSUE TITLE
NullPointerException on startup - "because restrictedPart is null"

### ISSUE THREAD

**Issue by encircled** [hibernate/hibernate-reactive#1779]
This simple example fails on startup since 2.x - https://github.com/encircled/hibernate-reactive-bug.  
Seems like it is caused by null in `EntityMappingType.identifierMapping`

hibernate: 6.3.1.Final
hibernate.reactive: 2.0.6.Final
vertx: 4.4.5
jdk: temurin 17.02
os: windows 10

```
Caused by: org.hibernate.MappingException: Could not instantiate persister org.hibernate.reactive.persister.entity.impl.ReactiveSingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:103)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:75)
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.processBootEntities(MappingMetamodelImpl.java:243)
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:181)
	at org.hibernate.internal.SessionFactoryImpl.initializeMappingModel(SessionFactoryImpl.java:323)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:273)
	at org.hibernate.reactive.session.impl.ReactiveSessionFactoryImpl.<init>(ReactiveSessionFactoryImpl.java:32)
	at org.hibernate.reactive.provider.service.ReactiveSessionFactoryBuilder.build(ReactiveSessionFactoryBuilder.java:38)
	at org.hibernate.reactive.provider.impl.ReactiveEntityManagerFactoryBuilder.build(ReactiveEntityManagerFactoryBuilder.java:63)
	... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.hibernate.metamodel.mapping.ModelPart.getPartName()" because "restrictedPart" is null
	at org.hibernate.loader.ast.internal.LoaderSelectBuilder.determineWhetherToForceIdSelection(LoaderSelectBuilder.java:454)
	at org.hibernate.loader.ast.internal.LoaderSelectBuilder.<init>(LoaderSelectBuilder.java:419)
	at org.hibernate.loader.ast.internal.LoaderSelectBuilder.<init>(LoaderSelectBuilder.java:434)
	at org.hibernate.loader.ast.internal.LoaderSelectBuilder.createSelect(LoaderSelectBuilder.java:245)
	at org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.createLoadPlan(SingleIdEntityLoaderStandardImpl.java:182)
	at org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.lambda$new$0(SingleIdEntityLoaderStandardImpl.java:41)
	at org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.<init>(SingleIdEntityLoaderStandardImpl.java:62)
	at org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.<init>(SingleIdEntityLoaderStandardImpl.java:38)
	at org.hibernate.reactive.loader.ast.internal.ReactiveSingleIdEntityLoaderStandardImpl.<init>(ReactiveSingleIdEntityLoaderStandardImpl.java:51)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractPersisterDelegate.createReactiveSingleIdEntityLoader(ReactiveAbstractPersisterDelegate.java:143)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractPersisterDelegate.<init>(ReactiveAbstractPersisterDelegate.java:81)
	at org.hibernate.reactive.persister.entity.impl.ReactiveSingleTableEntityPersister.<init>(ReactiveSingleTableEntityPersister.java:70)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:92)
	... 12 more

```

**Comment by radovanradic** [comment]
Might need to wait for 2.1.0 as per https://github.com/hibernate/hibernate-reactive/issues/1767#issuecomment-1727908499

Btw, does someone know when can we expect 2.1.0 release?

**Comment by blafond** [comment]
@encircled  FYI... I was able to reproduce your test.. thx for the reproducer.

**Comment by blafond** [comment]
@encircled Couple things in your project set-up

You had added an ORM dependency to your pom.xml of 6.3.1.Final but your Hibernate Reactive version is 2.0.6.Final which is built against ORM's **6.2.11.Final**.

- Remove the ORM dependency **<hibernate.version>6.3.1.Final</hibernate.version>** and building reactive will pull in the correct ORM version.

You've also got **kotlin** dependencies defined but you have only Java files defined.

You don't need **vertx-sql-client** dependency either if you have **vertx-mysql-client**

Locally I set up a java package containing **Main.java** and your  **TestEntity.java** and running a local *mysql* instance and was able to run the test below. 
```
public class Main {

    public static void main(String[] args) throws Exception {
        try (EntityManagerFactory emf = Persistence.createEntityManagerFactory("reactiveTest")) {
            Stage.SessionFactory factory = emf.unwrap(Stage.SessionFactory.class);
            factory.withTransaction((session, tx) -> session.persist(new TestEntity())).toCompletableFuture().join();
        }
    }

}
```

**Comment by DavideD** [comment]
> Btw, does someone know when can we expect 2.1.0 release?

We are waiting for the next ORM release

**Comment by DavideD** [comment]
@radovanradic I've forked your project and change the configuration here: https://github.com/DavideD/hibernate-reactive-bug

A few notes:
* I'm not familiar with Kotlin, there are probably smarter way to set up and refactor the project
* I've started a remote MariaDB server because the dependency you were using didn't work for me
* Hibernate ORM is  transitive dependency of Hibernate Reactive, no need to specify it
* Vert.x SQL client is a transitive dependency of the MariaDB client, no need to add it

In the end the issue is in the way you've set up the project with Kotlin, not a Hibernate Reactive one.

**Comment by encircled** [comment]
Sorry for the misleading about Kotlin, folder name is just a leftover since I'm using kotlin by default. Anyway, the producer has no dependency on kotlin and is pure java. 

The real problem was ORM version indeed, but I used what is mentioned as "compatible" in readme, probably should be updated - https://github.com/hibernate/hibernate-reactive/blob/288306131249b650f978e521badf6472c0c71cbd/README.md

**Comment by DavideD** [comment]
That's the README of the `main` branch, the README for Hibernate Reactive 2.0.6 is [here](I can see how that can be confusing, but that's the README). Or, you can check the website: [Hibernate Reactive 2.0](https://hibernate.org/reactive/releases/2.0/)

But I can see how that can be confusing.
