### ISSUE TITLE
query cache

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#247]
Closely related to #184, we should test the query cache, and if it's working, add the methods to the `Query` interfaces that are needed for managing it.

**Comment by gavinking** [comment]
As reported by @DavideD in #298, the query cache doesn't work when the query result set contains entity instances that aren't themselves cached.

This is likely quite easy to fix.

```
Unexpected access to the database
org.hibernate.AssertionFailure: Unexpected access to the database
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.onLoad(DefaultReactiveLoadEventListener.java:102)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:113)
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1184)
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1049)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.internalLoad(ReactiveSessionImpl.java:148)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:697)
```

**Comment by gavinking** [comment]
@DavideD It would be nice to know what exactly was the test you ran that resulted in the above error.

**Comment by DavideD** [comment]
I've created this branch with the test case: https://github.com/DavideD/hibernate-reactive/tree/247-Testcase
This is the test case: https://github.com/DavideD/hibernate-reactive/commit/4b395d5d713df00e94aa632cace3ba7809f3012e
It requires an `import.sql` maybe you know a way to avoid that?

The error is different now but I think it's a result of the latest changes. I didn't make much progress on solving this issue, if you want to have a look at it maybe you can solve it quickly.

**Comment by DavideD** [comment]
I will get back to this now

**Comment by DavideD** [comment]
Done
