### ISSUE TITLE
Support auto-generated IDs without calling JDBC

### ISSUE THREAD

**Issue by FroMage** [hibernate/hibernate-reactive#264]
It looks like this should work, but I'm getting JDBC requirements for this sort of ID:

```java
    @Id
    @GeneratedValue
    public Long id;
```

```
java.lang.UnsupportedOperationException: The application must supply JDBC connections
	at org.hibernate.engine.jdbc.connections.internal.UserSuppliedConnectionProviderImpl.getConnection(UserSuppliedConnectionProviderImpl.java:44)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:90)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:75)
	at org.hibernate.id.enhanced.SequenceStructure$1.getNextValue(SequenceStructure.java:93)
	at org.hibernate.id.enhanced.NoopOptimizer.generate(NoopOptimizer.java:40)
	at org.hibernate.id.enhanced.SequenceStyleGenerator.generate(SequenceStyleGenerator.java:523)
	at org.hibernate.reactive.event.impl.AbstractReactiveSaveEventListener.generateId(AbstractReactiveSaveEventListener.java:172)
	at org.hibernate.reactive.event.impl.AbstractReactiveSaveEventListener.reactiveSaveWithGeneratedId(AbstractReactiveSaveEventListener.java:154)
	at org.hibernate.reactive.event.impl.DefaultReactivePersistEventListener.entityIsTransient(DefaultReactivePersistEventListener.java:178)
	at org.hibernate.reactive.event.impl.DefaultReactivePersistEventListener.reactiveOnPersist(DefaultReactivePersistEventListener.java:126)
	at org.hibernate.reactive.event.impl.DefaultReactivePersistEventListener.reactiveOnPersist(DefaultReactivePersistEventListener.java:56)
```

Even though probably `SequenceReactiveIdentifierGenerator` should have the right bits, no?

**Comment by FroMage** [comment]
On Quarkus it doesn't look like `ReactiveIdentifierGeneratorFactoryInitiator.initiateService` is ever called, even though `ReactiveIdentifierGeneratorFactoryInitiator` is properly wired in.

**Comment by FroMage** [comment]
Forget it, this is a Quarkus bug.

**Comment by FroMage** [comment]
Moved to https://github.com/quarkusio/quarkus/issues/10187
