### ISSUE TITLE
PgException leaks to the user

### ISSUE THREAD

**Issue by FroMage** [hibernate/hibernate-reactive#280]
I attempted to persist an entity with a unicity constraint which should fail, and I got this:

```
io.vertx.pgclient.PgException: duplicate key value violates unique constraint "uk_1l3x2swifgj81xgvqivp7teto"
	at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:29)
	at io.vertx.pgclient.impl.codec.QueryCommandBaseCodec.handleErrorResponse(QueryCommandBaseCodec.java:57)
	at io.vertx.pgclient.impl.codec.ExtendedQueryCommandBaseCodec.handleErrorResponse(ExtendedQueryCommandBaseCodec.java:70)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:233)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:122)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:102)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

While I expected to have a `PersistenceException` in the ORM version. I assume this is a bug, right?

**Comment by gbadner** [comment]
@FroMage, yes, this sounds like a bug.

**Comment by gavinking** [comment]
Well, are we going to keep wrapping database exceptions? I mean, the motivation for doing that in Hibernate ORM was really that `SQLException` was a checked exception.

Here we don’t have that problem.

So it’s not quite so clear that it’s necessary.

**Comment by DavideD** [comment]
I think in this case we have to, people might want to try a different db and based on the connection driver we are using it could throw a different exception each time

**Comment by gavinking** [comment]
That’s a good point.

**Comment by gavinking** [comment]
Although, one could argue that this is the result of a (in principle fixable) lack of abstraction in the Vert.x API...

**Comment by DavideD** [comment]
We could have other implementation for the ReactiveConnection API other than Vert.x and  we would end up with the same issue. Not sure how likely it is though.

Still, vert.x having a common class for this would be nice.

**Comment by FroMage** [comment]
Well, so far the driver classes haven't leaks in my user API, so I'd rather keep on having to deal with Hibernate types if we can keep it that way. Unless we're talking about super-specific driver/db features, but unicity constraints being defined using a JPA annotation, I don't think this qualifies.

**Comment by FroMage** [comment]
Thanks.
