### ISSUE TITLE
Test works locally but fails on CI

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#348]
While I was working on #342 I've added the following test:

```
 	@Test
	public void testTransientExceptionWithMutiny(TestContext context) throws Exception {
		final SampleEntity sampleEntity = new SampleEntity();
		sampleEntity.firstKeyId = 1L;
		sampleEntity.secondKeyId = 2L;

		test( context, getMutinySessionFactory()
				.withTransaction( (session, transaction) -> session.persist( sampleEntity ) )
				.then( () -> getMutinySessionFactory()
						.withTransaction( (session, tx) -> {
							final SampleJoinEntity sampleJoinEntity = new SampleJoinEntity();
							sampleJoinEntity.sampleEntity = sampleEntity;
							sampleEntity.sampleJoinEntities.add( sampleJoinEntity );
							return session.persist( sampleJoinEntity );
						} )
				)
				.onItem().invoke( session -> context.fail( "Expected exception not thrown" ) )
				.onFailure().recoverWithUni( throwable -> {
					context.assertEquals( IllegalStateException.class, throwable.getClass() );
					context.assertEquals( TransientPropertyValueException.class, throwable.getCause().getClass() );
					return Uni.createFrom().nullItem();
				} )
		);
	}
```

This test checks that the operation throws an exception of type `IllegalStateException` and the cause is `TransientPropertyValueException`.

What happens on CI is this:

```
Gradle Test Executor 1 > org.hibernate.reactive.types.JoinColumnsTest > testTransientExceptionWithMutiny FAILED
    java.lang.AssertionError: Not equals : class java.lang.IllegalStateException != class io.smallrye.mutiny.CompositeException
        at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:362)
        at io.vertx.ext.unit.impl.TestContextImpl.assertEquals(TestContextImpl.java:258)
        at io.vertx.ext.unit.impl.TestContextImpl.assertEquals(TestContextImpl.java:245)
        at org.hibernate.reactive.types.JoinColumnsTest.lambda$testTransientExceptionWithMutiny$16(JoinColumnsTest.java:128)

    io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
    	[Exception 0] io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
    	[Exception 0] java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : org.hibernate.reactive.types.JoinColumnsTest$SampleJoinEntity.sampleEntity -> org.hibernate.reactive.types.JoinColumnsTest$SampleEntity
    	[Exception 1] java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : org.hibernate.reactive.types.JoinColumnsTest$SampleJoinEntity.sampleEntity -> org.hibernate.reactive.types.JoinColumnsTest$SampleEntity
    	[Exception 1] java.lang.AssertionError: Not equals : class java.lang.IllegalStateException != class io.smallrye.mutiny.CompositeException
        at io.smallrye.mutiny.operators.UniOnItemTransformToUni.invokeAndSubstitute(UniOnItemTransformToUni.java:36)
        at io.smallrye.mutiny.operators.UniOnFailureFlatMap$1.onFailure(UniOnFailureFlatMap.java:47)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.onFailure(UniSerializedSubscriber.java:85)
        at io.smallrye.mutiny.operators.UniOnItemConsume$1.onFailure(UniOnItemConsume.java:50)
```

It seems like the same exception is caught twice and therefore Mutiny throws a `CompositeException` instead of the expected one

This is the class: https://github.com/hibernate/hibernate-reactive/blob/822619ca60236f6fe9a23e387bd7be169d95d8c3/hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JoinColumnsTest.java#L126

**Comment by DavideD** [comment]
Link to one of the failing jobs: https://github.com/hibernate/hibernate-reactive/runs/1071327661?check_suite_focus=true

**Comment by DavideD** [comment]
I don't know what causing the issue but it's not critical and we check the exception anyway with stages.
I've relaxed the test in my PR: https://github.com/hibernate/hibernate-reactive/pull/345/files#diff-79a97e710e81d50312c5f7ae7c173379R162

We can think about it again if it happens again.
