### ISSUE TITLE
HQLQueryTest.cleanDb throws NullPointerException on scheduled job

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#418]
It doesn't always happen but we might be able to handle it.

```
Gradle Test Executor 1 > org.hibernate.reactive.HQLQueryTest > testAutoFlushOnResultList FAILED
    java.lang.NullPointerException
        at org.hibernate.engine.internal.StatefulPersistenceContext.clear(StatefulPersistenceContext.java:236)
        at org.hibernate.reactive.engine.impl.ReactivePersistenceContextAdapter.clear(ReactivePersistenceContextAdapter.java:118)
        at org.hibernate.internal.SessionImpl.cleanupOnClose(SessionImpl.java:531)
        at org.hibernate.internal.AbstractSharedSessionContract.setClosed(AbstractSharedSessionContract.java:353)
        at org.hibernate.internal.AbstractSharedSessionContract.close(AbstractSharedSessionContract.java:346)
        at org.hibernate.internal.SessionImpl.closeWithoutOpenChecks(SessionImpl.java:385)
        at org.hibernate.internal.SessionImpl.close(SessionImpl.java:361)
        at org.hibernate.reactive.session.impl.ReactiveSessionImpl.close(ReactiveSessionImpl.java:1324)
        at org.hibernate.reactive.stage.impl.StageSessionImpl.close(StageSessionImpl.java:450)
        at org.hibernate.reactive.BaseReactiveTest.openSession(BaseReactiveTest.java:165)
        at org.hibernate.reactive.HQLQueryTest.cleanDb(HQLQueryTest.java:48)
```

https://github.com/hibernate/hibernate-reactive/runs/1290593651?check_suite_focus=true#step:5:403

**Comment by gavinking** [comment]
interesting, i've never seen this even once.

**Comment by DavideD** [comment]
Me neither, it seems to only happen on CI

**Comment by DavideD** [comment]
I think we can close this one. It doesn't seem to happen anymore and I think it was more related to the GitHub workflow than our code.
