### ISSUE TITLE
Run tests in the Vert.x Loop Thread

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#478]
Our assumptions was that a test would run in a single Vert.x Event  loop thread. But Vert.x Unit run by default in a JUnit thread.
We need to apply the rule described [in this section of the Vert.x docs](https://vertx.io/docs/vertx-unit/java/#_running_a_test_on_a_vert_x_context
) to make sure that we run the tests as expected.

**Comment by DavideD** [comment]
@gavinking is this correct? ^

**Comment by gavinking** [comment]
I suppose so. I mean, perhaps this is not a critical thing to do, but it seems to me that this is what we always really intended to happen, isn't it?

**Comment by DavideD** [comment]
Yes, I think so.

It's probably not critical because our tests are simple at the moment. It could become critical down the road if we add more complex tests.

If it's only about adding a rule to the base test class I don't see why not.

**Comment by gavinking** [comment]
Yup. Agreed.

**Comment by DavideD** [comment]
Interesting, now that everything runs  in a single Vert.x event loop thread, Vert.x complains because our schemaDrop operations are blocking: https://github.com/hibernate/hibernate-reactive/blob/4e244618617999c5f213c8a47471c6ce4077b6ff/hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveGenerationTarget.java#L68

**Comment by DavideD** [comment]
THis is the exception I'm having:
```
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.7/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
	at java.base@11.0.7/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.7/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	at java.base@11.0.7/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
	at app//org.hibernate.reactive.provider.service.ReactiveGenerationTarget.release(ReactiveGenerationTarget.java:68)
	at app//org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:131)
	at app//org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:112)
	at app//org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:145)
	at app//org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
	at app//org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:316)
	at app//org.hibernate.reactive.session.impl.ReactiveSessionFactoryImpl.<init>(ReactiveSessionFactoryImpl.java:33)
	at app//org.hibernate.reactive.provider.service.ReactiveSessionFactoryBuilder.build(ReactiveSessionFactoryBuilder.java:52)
	at app//org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708)
	at app//org.hibernate.reactive.BaseReactiveTest.before(BaseReactiveTest.java:127)
```

**Comment by gavinking** [comment]
Ah, right, that makes sense.

I guess we need to dispatch them on a worker thread, or something.

**Comment by DavideD** [comment]
I'll try that, Thanks

**Comment by DavideD** [comment]
Wait... but if I add them to a worker thread, how can I guarantee that the Table of the schema is created before running the test?

**Comment by gavinking** [comment]
That I do not know.
