### ISSUE TITLE
orphan removal unsupported

### ISSUE THREAD

**Issue by pqab** [hibernate/hibernate-reactive#506]
Hi, we are facing an issue when using `orphanRemoval`, cascade goes into `onDelete` instead of `reactiveOnDelete`, and it throws an `UnsupportedOperationException`

## Example

Product
```
@Entity
@Table(name = "PRODUCT")
public class Product {

    @ManyToOne(targetEntity = Shop.class, cascade = MERGE)
    @JoinColumn(name = "SHOP_ID", referencedColumnName = "ID")
    private Shop shop;
   
    ...
}
```

Shop
```
@Entity
@Table(name = "SHOP")
public class Shop {

    @OneToMany(mappedBy = "shop", cascade = ALL, fetch = EAGER, orphanRemoval = true)
    private List<Product> productList = new ArrayList<>();

    ...
}
```

Main application
```
EntityManagerFactory emf = Persistence.createEntityManagerFactory("mysql");
Stage.SessionFactory sessionFactory = emf.unwrap(Stage.SessionFactory.class);

sessionFactory.withTransaction((session, transaction) -> {

        Shop s1 = Shop.builder().name("s1").build();
        s1.addProduct(Product.builder().name("ap1").build());
        s1.addProduct(Product.builder().name("ap2").build());
        s1.addProduct(Product.builder().name("ap3").build());
        s1.addProduct(Product.builder().name("ap4").build());

        // create
        return session.merge(s1)
                    .thenCombine(session.flush(), (s, v) -> s);
})
.thenCompose(t1 -> {
        return sessionFactory.withTransaction((session, transaction) -> {
            
            // get
            return session.find(Shop.class, t1.getId())
                    .thenCompose(s2 -> {

                        // update
                        s2.setName("s2");
                        s2.getProductList().clear();
                        s2.addProduct(Product.builder().name("bp5").build());
                        s2.addProduct(Product.builder().name("bp6").build());
                        s2.addProduct(Product.builder().name("bp7").build());

                        // update
                        return session.merge(s2);
                    })
                    .thenCombine(session.flush(), (s, v) -> s);
        });
});
```

## Stacktrace

```
java.util.concurrent.CompletionException: javax.persistence.PersistenceException: org.hibernate.HibernateException: javax.persistence.PersistenceException: org.hibernate.HibernateException: java.lang.UnsupportedOperationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:824)
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:110)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.doFlush(ReactiveSessionImpl.java:800)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.reactiveAutoflush(ReactiveSessionImpl.java:787)
	at org.hibernate.reactive.stage.impl.StageSessionImpl$Transaction.flush(StageSessionImpl.java:409)
	at org.hibernate.reactive.stage.impl.StageSessionImpl$Transaction.lambda$execute$2(StageSessionImpl.java:391)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	...
Caused by: java.lang.UnsupportedOperationException
	at org.hibernate.reactive.event.impl.DefaultReactiveDeleteEventListener.onDelete(DefaultReactiveDeleteEventListener.java:86)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:113)
	at org.hibernate.internal.SessionImpl.fireDelete(SessionImpl.java:924)
	... 93 more
```

## Sample application

https://github.com/pqab/orphanRemoval-example

## Environment Information

- Version: 1.0.0.Alpha11

**Comment by gavinking** [comment]
Ah yes, IIRC we don't support orphan removal, and I probably forgot to document that.

**Comment by semistone** [comment]
> Ah yes, IIRC we don't support orphan removal, and I probably forgot to document that.

do you have plan to support it in the future?

**Comment by gavinking** [comment]
I'm playing with this right now. Let's see if it's easy.

**Comment by gavinking** [comment]
Well, it might not be too hard. Let's see how I go.

**Comment by gavinking** [comment]
Seem to have it working 🤷‍♂️

**Comment by gavinking** [comment]
Fixed.
