### ISSUE TITLE
UnionSubclassInheritanceTest failure on CI with CockroachDB

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#659]
Sometimes on CI, [org.hibernate.reactive.UnionSubclassInheritanceTest fails](https://github.com/hibernate/hibernate-reactive/runs/2067495090?check_suite_focus=true#step:5:688) with CockroachDB:
```
Gradle Test Executor 1 > org.hibernate.reactive.UnionSubclassInheritanceTest > testQueryUpdate FAILED
    java.util.concurrent.CompletionException: io.vertx.pgclient.PgException: { "message": "restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): \"sql txn\" meta={id=09a0723a key=/Table/SystemConfigSpan/Start pri=0.00673528 epo=0 ts=1615301122.463914523,1 min=1615301122.439479102,0 seq=23} lock=true stat=PENDING rts=1615301122.439479102,0 wto=false max=1615301122.939479102,0", "severity": "ERROR", "code": "40001", "hint": "See: https://www.cockroachlabs.com/docs/v20.2/transaction-retry-error-reference.html#retry_serializable" }
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:783)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at org.hibernate.reactive.pool.impl.Handlers.lambda$toCompletionStage$0(Handlers.java:29)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:128)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:198)
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43)
        at io.vertx.sqlclient.impl.TransactionImpl.lambda$txCommand$2(TransactionImpl.java:169)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:128)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:198)
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
        at io.vertx.pgclient.impl.PgSocketConnection.lambda$doSchedule$2(PgSocketConnection.java:149)
        at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46)
        at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:258)
        at io.vertx.pgclient.impl.PgSocketConnection.handleMessage(PgSocketConnection.java:94)
        at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:96)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:90)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:378)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:52)
        at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:294)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:24)
        at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:377)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:153)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:78)
        at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:139)
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:226)
        at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:86)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        io.vertx.pgclient.PgException: { "message": "restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): \"sql txn\" meta={id=09a0723a key=/Table/SystemConfigSpan/Start pri=0.00673528 epo=0 ts=1615301122.463914523,1 min=1615301122.439479102,0 seq=23} lock=true stat=PENDING rts=1615301122.439479102,0 wto=false max=1615301122.939479102,0", "severity": "ERROR", "code": "40001", "hint": "See: https://www.cockroachlabs.com/docs/v20.2/transaction-retry-error-reference.html#retry_serializable" }
            at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:31)
            at io.vertx.pgclient.impl.codec.QueryCommandBaseCodec.handleErrorResponse(QueryCommandBaseCodec.java:57)
            at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:236)
            at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:122)
            at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:102)
            ... 17 more
```

**Comment by DavideD** [comment]
I've just realised that this error is the same as this other one: https://github.com/hibernate/hibernate-reactive/issues/675
And there is an article about it on the Cockroach website: https://www.cockroachlabs.com/docs/v20.2/transaction-retry-error-reference.html#retry_serializable

My understanding of this issue is that's it requires a better tuning of CockroachDB, but because we are using it for testing we can accept the fact that it will happen occasionally. I'm happy to be proven wrong if somebody has a solution.

Closing the issue for now.
