### ISSUE TITLE
Query projection bug

### ISSUE THREAD

**Issue by FroMage** [hibernate/hibernate-reactive#723]
As reported in https://github.com/quarkusio/quarkus/issues/15239 and simplified for pure HR, the following produces an exception:

```java
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "dog", schema = "example" )
public class Dog {

    @Id
    @GeneratedValue
    public Integer id;

    @Basic
    public String name;

    @Basic
    public String race;

    @ManyToOne
    public Person owner;
    
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public Person getOwner() {
        return owner;
    }
    
    public void setOwner(Person owner) {
        this.owner = owner;
    }

    public String getRace() {
        return race;
    }
    
    public void setRace(String race) {
        this.race = race;
    }
}
```

```java
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "person", schema = "example")
public class Person {

    @Id
    @GeneratedValue(generator = "id_seq", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "id_seq", sequenceName = "id_seq", schema = "example")
    private long id;

    @Basic
    private long birthdate;

    @Basic
    private String name;

    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Dog> dogs = new ArrayList<>();

    public Person() {
    }
    
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getBirthdate() {
        return birthdate;
    }
    
    public void setBirthdate(long birthdate) {
        this.birthdate = birthdate;
    }

    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public List<Dog> getDogs() {
        return dogs;
    }
    
    public void setDogs(List<Dog> dogs) {
        this.dogs = dogs;
    }
}

```

```java
import java.util.Collection;

public class PersonDto {
    public String name;
    public Collection<Dog> dogs;
    
    public PersonDto(String name, Collection<Dog> dogs) {
        this.name = name;
        this.dogs = dogs;
    }
}
```

```java
import java.util.List;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.hibernate.reactive.mutiny.Mutiny;

import com.example.model.controller.Dog;
import com.example.model.controller.Person;
import com.example.model.controller.PersonDto;

import io.smallrye.mutiny.Uni;

@Path("/")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@ApplicationScoped
public class ExampleResource {

    @Inject
    private Mutiny.Session session;

    @GET
    @Path("init")
    @Produces(MediaType.TEXT_PLAIN)
    public Uni<String> init() {
        final Person person = new Person();
        person.setName("person name");
        person.setBirthdate(1);
        final Dog dog = new Dog();
        dog.setName("dog name");
        dog.setRace("race 1");
        dog.setOwner(person);
        return session.withTransaction(t -> {
            return session.persist(person)
                    .chain(() -> session.persist(dog))
                    .replaceWith("ok");
        });
    }

    @GET
    @Path("people")
    public Uni<List<PersonDto>> getListOfPerson() {
        return session.<PersonDto>createQuery("SELECT NEW com.example.model.controller.PersonDto(name, dogs) FROM Person").getResultList();
    }
}
```

Exception is:

```
Hibernate: 
    select
        person0_.name as col_0_0_,
        {non-qualified-property-ref} as col_1_0_ 
    from
        example.person person0_ 
    inner join
        example.dog dogs1_ 
            on person0_.id=dogs1_.owner_id
2021-04-23 16:44:21,472 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-17) failed to execute statement [select person0_.name as col_0_0_, {non-qualified-property-ref} as col_1_0_ from example.person person0_ inner join example.dog dogs1_ on person0_.id=dogs1_.owner_id]
2021-04-23 16:44:21,472 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-17) could not execute query: java.util.concurrent.CompletionException: io.vertx.pgclient.PgException: syntax error at or near "{"
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.hibernate.reactive.pool.impl.Handlers.lambda$toCompletionStage$0(Handlers.java:29)
	at io.vertx.sqlclient.impl.SqlResultHandler.fail(SqlResultHandler.java:103)
	at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:89)
	at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:33)
	at io.vertx.sqlclient.impl.command.CommandBase.fail(CommandBase.java:31)
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$prepareCommand$2(SocketConnectionBase.java:230)
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:241)
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:88)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:78)
	at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:138)
	at io.vertx.pgclient.impl.codec.PrepareStatementCommandCodec.handleReadyForQuery(PrepareStatementCommandCodec.java:94)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:226)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:86)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.vertx.pgclient.PgException: syntax error at or near "{"
	at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:29)
	at io.vertx.pgclient.impl.codec.PrepareStatementCommandCodec.handleErrorResponse(PrepareStatementCommandCodec.java:88)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:236)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:122)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:102)
	... 17 more

```

**Comment by gavinking** [comment]
But ... since when does Hibernate even support a to-one association in `select new`? Are we 100% certain this works in Hibernate ORM core?

**Comment by gavinking** [comment]
Just checked. Neither Hibernate nor JPA allows a to-one collection reference in a `select` list. Surely the error message could be improved, but I'm supposing that that's an issue with the "old" (Hibernate 5.x) query parser.

**Comment by FroMage** [comment]
Haha, OK. Yeah, that's a confusing error, but if it's fine with the new parser, fine. Thanks!
