### ISSUE TITLE
Setting hibernate logging to debug causes NullPointerException

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#726]
To quickly see it, it's enough to set this in our test suite:
```
logger.hibernate.name =	org.hibernate
logger.hibernate.level = debug
```
The Exception:
```
Caused by: java.lang.NullPointerException
	at org.hibernate.reactive.persister.collection.impl.ReactiveBasicCollectionPersister.getSQLInsertRowString(ReactiveBasicCollectionPersister.java:141)
	at org.hibernate.persister.collection.AbstractCollectionPersister.logStaticSQL(AbstractCollectionPersister.java:693)
	at org.hibernate.persister.collection.AbstractCollectionPersister.<init>(AbstractCollectionPersister.java:529)
	at org.hibernate.persister.collection.BasicCollectionPersister.<init>(BasicCollectionPersister.java:59)
	at org.hibernate.reactive.persister.collection.impl.ReactiveBasicCollectionPersister.<init>(ReactiveBasicCollectionPersister.java:48)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createCollectionPersister(PersisterFactoryImpl.java:152)
```

It happens because Hibernate ORM log static queries in the `AbstractCollectionPersister` in the constructor.
The log operation calls `getSQLInsertRowString` that it is overriden by our subclasses because we need to parse the generated queries. Because the log is in the constructor, our parser has not been created yet.
See for example: https://github.com/hibernate/hibernate-reactive/blob/f283b6e8e4e0cb59add668ea70620af860924962/hibernate-reactive-core/src/main/java/org/hibernate/reactive/persister/collection/impl/ReactiveOneToManyPersister.java#L144

**Comment by gavinking** [comment]
@DavideD you assigned this to yourself, but let me know if you want me to do it.

**Comment by DavideD** [comment]
> @DavideD you assigned this to yourself, but let me know if you want me to do it.

Works for me :)

**Comment by DavideD** [comment]
I've assigned it to you @gavinking
