### ISSUE TITLE
merging a @ManyToOne association can call non-reactive code

### ISSUE THREAD

**Issue by nivinps** [hibernate/hibernate-reactive#951]
Hi, 
I need to update 'erp_campus_id' in 'erp_academic_year_detail' table. The same code will works If I used normal hibernate. But In hibernate-reactive it throws an exception. I am using 1.0.0.CR9 version.

```java
AcademicYearDetaisDBO dbo = sessionFactory.withSession(session -> session.createQuery("select dbo from AcademicYearDetaisDBO dbo where dbo.id=386",AcademicYearDetaisDBO.class).getSingleResult()).await().indefinitely();

dbo.setRecordStatus('A');
System.out.println(dbo.getCampusId().getId());//for example here campus id is 11
CampusDBO campusDBO = new CampusDBO();
campusDBO.setId(5);
dbo.setCampusId(campusDBO); // need to update as 5

sessionFactory.withTransaction((session, transaction) -> session.merge(dbo)).await().indefinitely(); // here it will throw an exception
```

```java
@Getter
@Setter
@Entity
@Table(name = "erp_academic_year_detail")
public class AcademicYearDetaisDBO implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "erp_academic_year_detail_id")
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "erp_campus_id")
    private CampusDBO campusId;

    @Column(name = "record_status")
    private char recordStatus;

    @Column(name = "created_users_id")
    private Integer createdUsersId;

    @Column(name = "modified_users_id")
    private Integer modifiedUsersId;
}
```

```java
@Entity
@Getter
@Setter
@Table(name="erp_campus")
public class CampusDBO implements Serializable {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        @Column(name="erp_campus_id")
        private  Integer id;

        @Column(name="campus_name")
        private String campusName;
}
```

Exception:

```
javax.persistence.PersistenceException: org.hibernate.HibernateException: java.util.concurrent.CompletionException: org.hibernate.reactive.event.impl.UnexpectedAccessToTheDatabase: Unexpected access to the database
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.reactive.session.impl.ReactiveExceptionConverter.convert(ReactiveExceptionConverter.java:31) ~[hibernate-reactive-core-1.0.0.CR9.jar:1.0.0.CR9]
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.lambda$fireMerge$28(ReactiveSessionImpl.java:842) ~[hibernate-reactive-core-1.0.0.CR9.jar:1.0.0.CR9]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[na:1.8.0_301]
	at com.ibm.asyncutil.iteration.AsyncTrampoline$TrampolineInternal.unroll(AsyncTrampoline.java:127) ~[asyncutil-0.1.0.jar:na]
	at com.ibm.asyncutil.iteration.AsyncTrampoline$TrampolineInternal.lambda$unroll$0(AsyncTrampoline.java:123) ~[asyncutil-0.1.0.jar:na]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[na:1.8.0_301]
	at io.vertx.core.Future.lambda$toCompletionStage$2(Future.java:360) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:102) ~[vertx-sql-client-4.1.2.jar:4.1.2]
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:35) ~[vertx-sql-client-4.1.2.jar:4.1.2]
	at io.vertx.core.Promise.complete(Promise.java:66) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.Promise.handle(Promise.java:51) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.Promise.handle(Promise.java:29) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72) ~[vertx-sql-client-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46) ~[vertx-sql-client-4.1.2.jar:4.1.2]
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:279) ~[vertx-sql-client-4.1.2.jar:4.1.2]
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:98) ~[vertx-sql-client-4.1.2.jar:4.1.2]
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:97) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:390) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:49) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:275) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:389) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155) ~[vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154) ~[vertx-core-4.1.2.jar:4.1.2]



Caused by: java.util.concurrent.CompletionException: org.hibernate.reactive.event.impl.UnexpectedAccessToTheDatabase: Unexpected access to the database
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:673) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:110) ~[na:1.8.0_301]
	at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.fetchAndCopyValues(DefaultReactiveMergeEventListener.java:484) ~[hibernate-reactive-core-1.0.0.CR9.jar:1.0.0.CR9]
	at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.lambda$null$8(DefaultReactiveMergeEventListener.java:348) ~[hibernate-reactive-core-1.0.0.CR9.jar:1.0.0.CR9]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110) ~[na:1.8.0_301]
	at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.lambda$entityIsDetached$10(DefaultReactiveMergeEventListener.java:348) ~[hibernate-reactive-core-1.0.0.CR9.jar:1.0.0.CR9]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[na:1.8.0_301]
	... 78 common frames omitted
Caused by: org.hibernate.reactive.event.impl.UnexpectedAccessToTheDatabase: Unexpected access to the database
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.onLoad(DefaultReactiveLoadEventListener.java:107) ~[hibernate-reactive-core-1.0.0.CR9.jar:1.0.0.CR9]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1215) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1080) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:697) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.type.EntityType.resolve(EntityType.java:464) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.type.ManyToOneType.resolve(ManyToOneType.java:240) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.type.EntityType.resolve(EntityType.java:457) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.type.EntityType.replace(EntityType.java:358) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.type.TypeHelper.replace(TypeHelper.java:167) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
	at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.copyValues(DefaultReactiveMergeEventListener.java:493) ~[hibernate-reactive-core-1.0.0.CR9.jar:1.0.0.CR9]
	at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.lambda$fetchAndCopyValues$14(DefaultReactiveMergeEventListener.java:484) ~[hibernate-reactive-core-1.0.0.CR9.jar:1.0.0.CR9]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[na:1.8.0_301]


```

**Comment by DavideD** [comment]
THanks @nivinps, I'm checking

**Comment by DavideD** [comment]
One problem with this code is that you are setting an association with an object that it's not managed.
The correct way to write this should be:
```
							sessionFactory.withTransaction( (session, transaction) -> {
								dbo.setCampusId( session.getReference( CampusDBO.class, 5 ) );
								return session.merge( dbo );
							} );
```

Assuming that the object exists in the db (because you are using a reference, Hibernate Reactive is not going to load it).

The other thing I had to change was this value:
```
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "erp_campus_id")
   private CampusDBO campusId;
```

@gavinking do you know why without the Lazy, it tries to access the database? (I can provide  a testcase if you need one)

That said, it's possible to rewrite your example this way:
```
sessionFactory
				.withTransaction( (session, tx) -> session
						.find( AcademicYearDetailsDBO.class, 386 ) // a query will work as well
						.invoke( dbo -> {
							dbo.setRecordStatus( 'A' );
							System.out.println( dbo.getCampusId().getId() );//for example here campus id is 11
							dbo.setCampusId( session.getReference( CampusDBO.class, 5 ) );
						} ) )
		);
```

Note that this way you don't have to merge and it will work for all cases (not sure if you can do it in your real use case).

**Comment by gavinking** [comment]
```java
CampusDBO campusDBO = new CampusDBO();
campusDBO.setId(5);
dbo.setCampusId(campusDBO); // need to update as 5
```

Well, OK, yes, @DavideD is quite right, this isn't the way you're supposed to go about setting a reference to an object that already exists in the database (not in regular Hibernate, nor in reactive.

> @gavinking do you know why without the Lazy, it tries to access the database?

I would have to stop through the code but I can think of a couple of scenarios:

- it might by trying to determine if the object is "saved" or "unsaved", or
- perhaps it's trying to obtain a snapshot of the previous state.

I'm not certain. (If you attach I test case I can figure it out.)

**Comment by DavideD** [comment]
See https://github.com/hibernate/hibernate-reactive/pull/952

**Comment by gavinking** [comment]
So the original code given above is a misuse of Hibernate, but this is nevertheless a bug.

**Comment by nivinps** [comment]
Thanks @DavideD @gavinking for your guidance and support

Our use case is a little different. So I prefer to merge. I can give you a brief.

Our micro service application using Spring Webflux. We splitted functionalities into three different files: controller, handler, transaction file. Controller mainly accepts front end data (DTO) and sends it to the handler file. Handler file mainly used for business logic. By using a handler file we are converting DTO data to entity data (includes many logics) . We have many 
` @ManyToOne` references and `@OneToMany `relationships in each entity. If we found any invalid data in the DTO object then we are sending some error response to the front end through the controller file. Mainly all business logic will be written in the handler file, after that it will create the entity. Finally this entity we are sending to the transaction file to persist/merge to the database.. In the transaction file we are writing database related activities. Writing queries for fetching data and persist/merge operations. The `sessionFactory` we used to write in the transaction file. . As @gavinking said, we might be misusing the hibernate by setting a reference to an object  ( `campusId `) in a bad approach (this logic we were writing in the handler file).  Any Suggestions would be greatly appreciated.

**Comment by gavinking** [comment]
> Any Suggestions would be greatly appreciated.

Well, I have no further suggestion beyond what @DavideD said above. Use:

```java
CampusDBO campusDBO = session.getReference( CampusDBO.class, 5 );
dbo.setCampusId(campusDBO);
```

instead of:

```java
CampusDBO campusDBO = new CampusDBO();
campusDBO.setId(5);
dbo.setCampusId(campusDBO);
```

What you're doing right now might *work*, at least if you're careful, but it's not how this API is intended to be used.

**Comment by nivinps** [comment]
> What you're doing right now might work, at least if you're careful, but it's not how this API is intended to be used.

OK @gavinking. Thank you once again.
